DIVIDEND_FORECAST_LOOKBACK_YEARS: 1
DIVIDEND_FORECAST_METHOD: "avg"
DIVIDEND_FORECAST_LOOKFORWARD_YEARS: 4
DAILY_BASIS: 365.25
OPTION_TIMESERIES_START_DATE: "2017-01-01"
VOL_EST_UPPER_BOUND: 5.0
VOL_EST_LOWER_BOUND: 0.01
N_PRECISION_GREEKS: 200
DX_THRESH: 0.001